- source/SAMRAI/solv/CellPoissonHypreSolver.C
- source/SAMRAI/solv/CellPoissonHypreSolver.h
- source/test/hypre/HyprePoisson.C
Revision based on pull request #32  by @jeanlucf22 .   Avoids temporary data copy when ghost data for source and destination match, and adds an optional argument to use a zero vector as the initial guess for the solution vector.
> More efficient HYPRE operations in CellPoissonHypreSolver

- CMakeLists.txt
- source/SAMRAI/algs/CMakeLists.txt
- source/SAMRAI/appu/CMakeLists.txt
- source/SAMRAI/geom/CMakeLists.txt
- source/SAMRAI/hier/CMakeLists.txt
- source/SAMRAI/math/CMakeLists.txt
- source/SAMRAI/mesh/CMakeLists.txt
- source/SAMRAI/pdat/CMakeLists.txt
- source/SAMRAI/solv/CMakeLists.txt
- source/SAMRAI/tbox/CMakeLists.txt
- source/SAMRAI/xfer/CMakeLists.txt
Update to the latest version of BLT, which removes ENABLE_COPY_HEADERS support.
> Remove ENABLE_COPY_HEADERS and update BLT

- source/SAMRAI/tbox/Scanner.C
The keyword [`register`](https://en.cppreference.com/w/cpp/keyword/register) is deprecated and removed in C++17.  This patch removes this hint from `SAMRAI/tbox/Scanner.C` which makes SAMRAI compile with C++17 enabled.
> Remove the register keyword from tbox/Scanner.C

- docs/CMakeLists.txt
Because of a type, the current `docs/CMakeLists.txt` was broken if `DOXYGEN_FOUND`. This patch fixes this and makes it possible to build the documentation from CMake.
> Fix typo and change add_doxygen_target to blt_add_doxygen_target.

- source/SAMRAI/tbox/ParallelBuffer.C
- source/SAMRAI/tbox/ParallelBuffer.h
The current behavior of `std::ostream` is to ignore `ParallelBuffer::xsputn(std::string, std::streamsize)` because it does not override the virtual function `std::streambuf::xsputn(const char*, std::streamsize)`. Instead, the default implementation of `std::streambuf::xsputn(const char*, std::streamsize)` calls `ParallelBuffer::overflow(int)` for each single character which causes a call to `sync()` and `outputString()` for each single character.
This patch fixes this and also adds the `override` keyword to the virtual function overrides of ParallelBuffer. Functions which are marked by override but do not override any virtual function will lead to compile time errors.
It is hard to come up with a Unit Test for this because there is no observable effect wrt correctness. 
Do you have a …
> Fix the virtual xsputn overload of tbox::ParallelBuffer

- source/SAMRAI/pdat/ArrayData.C
- source/SAMRAI/tbox/MessageStream.h
Removes extra vector buffer in packing and unpacking. Using the additional vectors, while nice from an implementation standpoint, requires many additional allocations and without a pool slows the calculation.
> tbox::MessageStream {un,}pack -> get{Read,Write}Buffer in pdat::ArrayData

- source/SAMRAI/tbox/ParallelBuffer.C
Change the used `std::string` constructor from `std::string(const char*)` to
`std::string(const char*, long n)` such that we do not invoke undefined
behavior if the pointer points to a single character which is not
null-terminated.
You can reproduce the error with enabled address / undefined sanitizer and
```cpp
#include <SAMRAI/tbox/SAMRAIManager.h>
#include <SAMRAI/tbox/SAMRAI_MPI.h>
#include <SAMRAI/tbox/PIO.h>
int main(int argc, char** argv)
{
SAMRAI::tbox::SAMRAI_MPI::init(&argc, &argv);
SAMRAI::tbox::SAMRAIManager::initialize();
SAMRAI::tbox::SAMRAIManager::startup();
SAMRAI::tbox::pout << '\n';
SAMRAI::tbox::SAMRAIManager::shutdown();
SAMRAI::tbox::SAMRAIManager::finalize();
SAMRAI::tbox::SAMRAI_MPI::finalize();
}
```
> This commit fixes an undefined behaviour in ParallelBuffer::xsputn

- source/CMakeLists.txt
This works in my local CI builds, where I use SAMRAI as a dependency and do not need to build the tests.
> Only conditionally add source/tests as subdirectory to CMake.

- cmake/SAMRAIMacros.cmake
- source/test/MblkEuler/CMakeLists.txt
- source/test/applications/ConvDiff/CMakeLists.txt
- source/test/applications/Euler/CMakeLists.txt
- source/test/applications/LinAdv/CMakeLists.txt
- source/test/mblktree/CMakeLists.txt
- source/test/mblktree/main-mbtree.C
- source/test/performance/MeshGeneration/CMakeLists.txt
- source/test/performance/TreeCommunication/CMakeLists.txt
- source/test/rank_group/main.C
The biggest change is to the samrai_add_tests macro, creating tests of 1, 2, and 4 MPI ranks when PARALLEL is true.
Some things remaining to be done:
> Parallel test changes

- source/SAMRAI/xfer/RefineSchedule.C
RefineSchedule when the domain is flat (1 cell) in one or more of the
mesh dimensions.
> Bux fix that enables a simplified internal Connector computation inside

- config/SAMRAI_config.h.cmake.in
- source/SAMRAI/tbox/CMakeLists.txt
Enables SILO in the cmake build system.
> Make cmake SILO flags work correctly

- CMakeLists.txt
Add some CMake code to detect if BLT is already loaded
and in use. This is helpful if SAMRAI is being built as
a submodule within another project.
> Allow building SAMRAI with a shared BLT

- source/test/applications/ConvDiff/CMakeLists.txt
- source/test/applications/Euler/CMakeLists.txt
- source/test/applications/LinAdv/CMakeLists.txt
- source/test/applications/LinAdv/test_inputs/test_nonuniform.2d.input
- source/test/applications/LinAdv/test_inputs/test_nonuniform.3d.input
- source/test/mblktree/main-mbtree.C
The tests in source/test/applications were not all testing against the baseline hdf5 boxes files correctly--they needed to be compiled with -DTESTING=1 and depend on testlib.  Also there were some spurious failures when HDF5 was disabled.
> Fixing some cmake test behavior

- cmake/CMakeConfigureFile.cmake
- config/SAMRAI_config.h.cmake.in
- source/test/MblkLinAdv/CMakeLists.txt
DEBUG_INITIALIZE_UNDEFINED, DEBUG_CHECK_ASSERTIONS, and DEBUG_CHECK_DIM_ASSERTIONS need to be turned on in debug builds in order for cmake debug builds to match the behavior of autoconf debug builds.
This caused one test, MblkLinAdv, to require a reordering of its library dependencies in order to link its executable.  I don't really understand why.
> Enable the debugging macros for cmake Debug builds

- source/SAMRAI/hier/MappingConnectorAlgorithm.C
- source/SAMRAI/tbox/ParallelBuffer.C
- source/SAMRAI/tbox/ParallelBuffer.h
A mutex call was double-locking due to recursion, and a thread-unsafe timer call was made within a threaded section of code.
> Fixing some OpenMP-related bugs

- source/SAMRAI/hier/BoxId.h
- source/SAMRAI/hier/GlobalId.h
GCC 9.2 Werror 
samrai/source/SAMRAI/hier/Box.h:309:14: error: implicitly-declared ‘SAMRAI::hier::BoxId& 
SAMRAI::hier::BoxId::operator=(const SAMRAI::hier::BoxId&)’ is deprecated [-Werror=deprecated- 
copy]
samrai/source/SAMRAI/hier/BoxId.h:37:7: error: implicitly-declared ‘SAMRAI::hier::GlobalId& 
SAMRAI::hier::GlobalId::operator=(const SAMRAI::hier::GlobalId&)’ is deprecated [-
Werror=deprecated-copy]
> implicitly declared deprecated

- source/SAMRAI/xfer/RefineTimeTransaction.C
- source/SAMRAI/xfer/RefineTimeTransaction.h
This is a first step toward fixing a bug that can occur due to RefineTimeTransaction passing a cell-centered Box to define the computation space for timeInterpolate() instead of a BoxOverlap object.
This PR doesn't fix the bug, but it causes calls to RefineTimeTransaction that don't truly need time interpolation to avoid calling timeInterpolate().  When timeInterpolate() has the same timestamp for the source and destination, its operations are equivalent to a copy or pack, but it is more efficient and straightforward to call the PatchData's copy/pack methods in that case.  This also allows runs that don't actually use time refinement to avoid triggering the aforementioned bug.  The bug will be directly addressed soon in another PR.
> Direct calls to copy/pack in RefineTimeTransaction

- source/SAMRAI/hier/VariableDatabase.C
- source/SAMRAI/hier/VariableDatabase.h
the current 
```
static VariableDatabase* s_variable_database_instance;
```
can end up being inlined in separate libraries such that there is more than one active VariableDatabase instance
> prevent multiple VariableDatabase instances across shared libraries

- source/SAMRAI/solv/CVODESolver.C
If left uninitialized in constructor, these flags may be used uninitialized and lead to undefined behavior
> Initialize uninitialzed flags

- CMakeLists.txt
- source/SAMRAI/pdat/FaceVariable.C
- source/SAMRAI/pdat/FaceVariable.h
- source/SAMRAI/pdat/NodeVariable.C
- source/SAMRAI/pdat/NodeVariable.h
- source/SAMRAI/pdat/OuterfaceVariable.C
- source/SAMRAI/pdat/OuterfaceVariable.h
- source/SAMRAI/pdat/OutersideData.C
- source/SAMRAI/pdat/OutersideVariable.C
- source/SAMRAI/pdat/OutersideVariable.h
- source/SAMRAI/pdat/SideVariable.C
- source/SAMRAI/pdat/SideVariable.h
- source/SAMRAI/solv/CartesianRobinBcHelper.C
- source/SAMRAI/solv/CartesianRobinBcHelper.h
- source/SAMRAI/solv/CellPoissonFACOps.C
- source/SAMRAI/solv/CellPoissonFACOps.h
- source/SAMRAI/solv/CellPoissonFACSolver.C
- source/SAMRAI/solv/CellPoissonHypreSolver.C
- source/SAMRAI/solv/CellPoissonHypreSolver.h
- source/SAMRAI/solv/SimpleCellRobinBcCoefs.C
- source/test/FAC_adaptive/AdaptivePoisson.C
- source/test/FAC_adaptive/AdaptivePoisson.h
- source/test/FAC_staticrefinement/FACPoisson.C
- source/test/nonlinear/ModifiedBratuProblem.C
- source/test/nonlinear/ModifiedBratuProblem.h
- source/test/sundials/CVODEModel.C
- source/test/sundials/CVODEModel.h
- source/test/vector/kvtest.C
Creates consistency between persistent and temporary data.  Next step is to provide flexibility to specify the allocator rather than using a default.
> Make all variables in code using HYPRE and Sundials solvers to use Umpire allocators when available

- source/SAMRAI/mesh/GriddingAlgorithm.C
- source/SAMRAI/mesh/GriddingAlgorithm.h
An assertion in a GriddingAlgorithm private member was testing that a pointer tag_to_finer that was passed as an argument was non-null. However, the pointer was never used in the method outside of the assertion so it didn't matter if it was null. This caused failures in certain cases that used "REFINE_BOXES" to set fixed refinement--those cases did not allocate the pointer and thus failed the assertion, but they also never needed to use the pointer, so the assertion failure was spurious.
This addresses issue #8
> Remove tag_to_fine ptr from a private method that didn't use it.

- RELEASE-NOTES
- docs/release/version-4.0.2
- source/SAMRAI/hier/Box.h
- source/SAMRAI/hier/BoxContainer.h
- source/SAMRAI/tbox/AsyncCommPeer.C
- source/SAMRAI/tbox/AsyncCommPeer.h
- source/SAMRAI/tbox/ExecutionPolicy.h
- source/SAMRAI/tbox/Schedule.C
- source/SAMRAI/tbox/Utilities.h
This is needed because of tbox::Schedule's usage of AsyncCommPeer and MessageStream. We have promised that MessageStream will create buffers using the stream Allocator held in the AllocatorDatabase, which is a pinned memory allocator by default. However, MessageStream can also be constructed to use an external buffer passed into the constructor, in which case the buffer could be anywhere and is not necessarily in pinned memory when we give the MessageStream to user code.
In particular, tbox::Schedule takes buffers created inside AsyncCommPeer and gives them to MessageStream as external buffers. These buffers have been allocated as CPU host buffers, so the MessageStream is provided to user code holding a host buffer rather than a buffer associated with the stream Allocator's promised …
> Add allocator set method to AsyncCommPeer

- source/SAMRAI/hier/Index.h
- source/SAMRAI/hier/IntVector.C
- source/SAMRAI/hier/IntVector.h
These classes should not be used inside device kernels.
> Remove SAMRAI_HOST_DEVICE from Index and IntVector

- source/SAMRAI/algs/MethodOfLinesIntegrator.C
This addresses issue #153 .
The sequence of inter-level operations in the Runge-Kutta loop was incorrect.  The changes here reorganize the iteration of an RK step in this loop as follows:
- Fill ghosts on all levels, including refinement operations where needed.
- Patch-based RK-step advance on all levels
- Coarsen data from finest to coarsest levels.
> Correct the sequence of inter-level data transfers in MethodOfLinesIntegrator

- source/SAMRAI/math/HierarchyCellDataOpsReal.C
- source/SAMRAI/math/HierarchyEdgeDataOpsReal.C
- source/SAMRAI/math/HierarchyFaceDataOpsReal.C
- source/SAMRAI/math/HierarchyNodeDataOpsReal.C
- source/SAMRAI/math/HierarchySideDataOpsReal.C
- source/SAMRAI/tbox/SAMRAI_MPI.h
Functions to compute length of a vector of data in Hierarchy*DataOpsReal.C are missing an MPI_Allreduce.
This PR makes it consistent with other functions in these classes. I also satisfy Sundials requirement of a global vector length.
The sundials tests in SAMRAI seem not to be sensitive to that fix and still pass.
> Fix computation of data length

- source/SAMRAI/hier/PatchHierarchy.C
These were incorrectly describing the windows in relation to the global origin of the mesh, rather than the local origin of each patch.
> Change blueprint nestset windows to be based on local patch origin

- source/SAMRAI/pdat/CMakeLists.txt
These are useful in downstream projects (like IBAMR).
> Install the M4 macros for array dimensions.

- source/SAMRAI/tbox/CMakeLists.txt
- source/SAMRAI/tbox/Collectives.h
- source/SAMRAI/tbox/GPUUtilities.C
- source/SAMRAI/tbox/GPUUtilities.h
This gives applications a way to indicate that their GPU-enabled code is running without GPUs.  We suppress the RAJA/CUDA parallel synchronize in this case.
> Add API allowing user code to set flag for using GPUs

- source/SAMRAI/pdat/ArrayDataOperationUtilities.C
This addresses the error reported in #145 and makes similar sections of the ArrayData code do the same thing.
> Change variable-sized array to fixed-size

- INSTALL-NOTES
- source/SAMRAI/pdat/ArrayView.h
- source/test/dataops/CMakeLists.txt
- source/test/dataops/cell_fillall.cpp
This makes things compatible with a recent change in RAJA where the upper bound of a range of indices is no longer automatically included as part of the range, so we needed to add +1 to our calls to keep things working.
> Adjust ArrayView to change in RAJA offset layout

- source/SAMRAI/algs/TimeRefinementIntegratorConnectorWidthRequestor.cpp
- source/test/applications/Euler/test_inputs/test_buffer.2d.input
- source/test/applications/Euler/test_inputs/test_buffer.3d.input
This fixes a bug where the default intra-level self connector width gets set to a large value due to a relatively large tag buffer size being specified in the input, but the tag buffer had no effect on the inter-level fine connector width.  This caused the possibility of a large difference between the self connector width and the fine connector width, which can cause bridge operations during generation of new levels to fail
The fix is to make sure that the fine connector width is equal to the self connector width divided by the refinement ration (rounded up if there is a remainder).
> Make fine connector widths large enough to handle large tag buffers

- source/SAMRAI/hier/MappingConnectorAlgorithm.cpp
- source/SAMRAI/hier/OverlapConnectorAlgorithm.cpp
MappingConnectorAlgorithm and OverlapConnectorAlgorithm used a constantly increasing static value for the MPI tags used in sends and receives, so that each invocation used a unique value. This may have been necessary in the past, but is not now, since we have strict error-checking to ensure that there are no stray messages lingering for any tag value.  The increasing values risk surpassing upper bounds for valid values of the MPI tags.
> Keep MPI tags in Connector algorithm classes constant

- CMakeLists.txt
- cmake/SAMRAIMacros.cmake
MIN_TEST_PROCS can be used to reduce the number of parallel executions of the tests during "make test". With default value 1, it runs all of the tests on 1,2,4 procs, as usual.  With value 2, it runs tests on 2 and 4 procs, and with value 4, it runs them only on 4 procs.
> Add cmake option MIN_TEST_PROCS

- source/SAMRAI/pdat/ArrayData.cpp
- source/SAMRAI/pdat/ArrayDataOperationUtilities.cpp
This changes some of the small arrays in ArrayData to the standard type and adds default initialization to eliminate some warnings on potential use of uninitialized data.
>  Change some C-style arrays to std::arrays and add default initialization
